# Generated by Django 6.0.5 on 2026-05-26 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0003_alter_tenantmodules_options_alter_tenants_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantPayments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("amount", models.IntegerField(default=0)),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenants",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Payment",
                "verbose_name_plural": "Tenant Payments",
                "db_table": "tenant_payments",
            },
        ),
    ]
