# Generated by Django 6.0.5 on 2026-05-25 04:35

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="users",
            managers=[
                ("objects", apps.users.models.UserManager()),
            ],
        ),
    ]
