# Generated by Django 6.0.5 on 2026-05-25 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_users_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="users",
            managers=[],
        ),
    ]
