# Generated by Django 6.0.5 on 2026-05-25 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_users_groups_users_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="users",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelTable(
            name="users",
            table="users",
        ),
    ]
