# Generated by Django 6.0.5 on 2026-05-25 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModulePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("standart_price", models.IntegerField(default=0)),
                ("standart_features", models.TextField()),
                ("pro_price", models.IntegerField(default=0)),
                ("pro_features", models.TextField()),
                ("premium_price", models.IntegerField(default=0)),
                ("premium_features", models.TextField()),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="module.module"
                    ),
                ),
            ],
        ),
    ]
