# Generated by Django 6.0.5 on 2026-05-25 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("module", "0002_moduleprice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="module",
            options={
                "ordering": ["order"],
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
            },
        ),
        migrations.AlterModelOptions(
            name="moduleprice",
            options={
                "verbose_name": "Module Price",
                "verbose_name_plural": "Module Prices",
            },
        ),
        migrations.AlterModelTable(
            name="module",
            table="module",
        ),
        migrations.AlterModelTable(
            name="moduleprice",
            table="module_price",
        ),
    ]
