# Generated by Django 6.0.5 on 2026-05-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("company_slug", models.CharField(max_length=10)),
                ("description", models.TextField()),
                ("phone_number", models.CharField(max_length=20)),
                ("full_name", models.CharField(max_length=100)),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("it", "IT"),
                            ("finance", "FINANCE"),
                            ("agro", "AGRO"),
                            ("retail", "RETAIL"),
                            ("logistics", "LOGISTICS"),
                            ("manufacturing", "MANUFACTURING"),
                            ("health", "HEALTH"),
                            ("education", "EDUCATION"),
                            ("media", "MEDIA"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("postal_code", models.CharField(max_length=10)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
            ],
        ),
    ]
