# Generated by Django 6.0.5 on 2026-05-25 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenantmodules"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tenantmodules",
            options={
                "verbose_name": "Tenant Module",
                "verbose_name_plural": "Tenant Modules",
            },
        ),
        migrations.AlterModelOptions(
            name="tenants",
            options={"verbose_name": "Tenant", "verbose_name_plural": "Tenants"},
        ),
        migrations.AlterModelTable(
            name="tenantmodules",
            table="tenant_modules",
        ),
        migrations.AlterModelTable(
            name="tenants",
            table="tenants",
        ),
    ]
